const dummyPosts = [
  {
    id: 0,
    vardas: 'Lukas',
    pavarde: 'Lukaitis',
    telefonas: '+3706336588',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'Matematikos Mokytojas',
    detalusAprasymas: 'Lorem ipsum dolor sit amet, consectetur.',
    kaina: '30',
    miestas: 'Kaunas',
    img: 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX20020039.jpg',
  },
  {
    id: 2,
    vardas: 'Tadas',
    pavarde: 'Tadaitis',
    telefonas: '+37061234567',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'Matematikos Mokytojas Kaunas',
    detalusAprasymas:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kaina: '15',
    miestas: 'Vilnius',
    img: 'https://pbs.twimg.com/media/DvW5JrOVAAU6kaJ.jpg',
  },
  {
    id: 4,
    vardas: 'Dalia',
    pavarde: 'Dalialia',
    telefonas: '+3706777777',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'Title 4',
    detalusAprasymas:
      'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kaina: '15',
    miestas: 'Vilnius',
    img: 'https://i.pinimg.com/736x/e9/4e/67/e94e67c4cd1809e4f88af578c6a8b94f.jpg',
  },
  {
    id: 1,
    vardas: 'Rafaelis',
    pavarde: 'Rafas',
    telefonas: '+3706999999',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'Mokytojas Silaniai',
    detalusAprasymas:
      'Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kaina: '15',
    miestas: 'Vilnius',
    img: 'https://st.depositphotos.com/1010751/5030/v/950/depositphotos_50301757-stock-illustration-concept-of-mathematical-brain-logo.jpg',
  },
  {
    id: 3,
    vardas: 'Mantas',
    pavarde: 'Mantaitis',
    telefonas: '+3706133333',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'j. Basanaviciaus Mokykla Kaunas',
    detalusAprasymas:
      'Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua.',
    kaina: '15',
    miestas: 'Vilnius',
    img: 'https://i.pinimg.com/originals/91/2f/be/912fbe16162e8c1882980bb3d12ab273.jpg',
  },
  {
    id: 5,
    vardas: 'Toams',
    pavarde: 'Tomaitis',
    telefonas: '+37063212222',
    elPastas: 'lukas.lukaitis@gmail.com',
    aprasymas: 'Gymnazija',
    detalusAprasymas:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kaina: '15',
    miestas: 'Vilnius',
    img: 'https://pbs.twimg.com/media/DvW5JrOVAAU6kaJ.jpg',
  },
];

export {dummyPosts};
